### ISSUE TITLE
Maintain minimum haddocks and coding style

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/AutoObsidian#1]
Hi guys, as I'm starting to read through the code, it would be _really_ helpful if it were documented properly.  We don't have to follow heavy process when writing research code, but reasonable docs is still pretty lightweight.

Please close this issue after adding:
- At least a one line haddock description at the top of every module that says what it is and why its there.  This is the most important bit I find when navigating.
- Haddocks for the most important functions.  For example, it's good for class definitions and methods to have haddocks, whereas the instances don't typically need them.  Even though it's small, right now I don't understand what all the parameters are doing in the `SearchMonad` class based on reading its definition.

Also, you may want to refer to [Johan Tibbell's Haskell Style guide](https://github.com/tibbe/haskell-style-guide).

**Comment by vollmerm** [comment]
Yeah, we've been slacking off on that during our hacking. I'll go through soon and document what we have.
